annapirova/mp-2023-pmi2

- Artem_Barinov/ЯМП-задания/ConsoleApplication1.vcxproj
- Artem_Barinov/ЯМП-задания/ConsoleApplication1.vcxproj.filters
- Artem_Barinov/ЯМП-задания/massive 1-4.cpp
- Artem_Barinov/ЯМП-задания/perestanovka.cpp
Вот готовый вариант. Кажется, всё правильно работает.
> С/Р перестановка - Баринов Артём

- Belyaev N/Kacca.c
Совместил 4 и 5 операцию кассы, т.к. они одинаковые по сути. В 4 чек по условию должен включать в себя общую сумму и к оплате. А 5 ещё раз выводит эти же результаты.
> Беляев Н. Kacca

- KASSA.c
Добавил функцию, которая считает сколько видов разных продуктов было куплено, а также функцию, отображающую какой продукт и в каком количестве купил пользователь. НУ и рассчитал общее количество отсканированных товаров в функции:("scan_product").
> VADIM_VLASOV_KASSA_2

- Artem_Barinov/ЯМП-задания/Sortirovki.cpp
Баринов Артём: сортировки для сдачи
> Sortirovki - slianiem dla sdachi

- kovalev/sort.c
> sort kovalev

- SORTIROVKI.c
Сделал двунаправленный пузырек, добавил функцию(массива копии), теперь сортировка идет лишь по исходному массиву и добавил функцию проверки массива на отсортированность, обе функции в самом начале программы.
> VLASOV_CORTIROVKI_2.0

- Ilyushkin N/bulls and cows.c
- Ilyushkin N/kontrolnaia rabota.c
- Ilyushkin N/ugadaika.c
- Ilyushkin N/zad 1.c
отправил задания быки и коровы угадайка и задание 1
> nikita ilyushkin

- Zhdankin/matrix24.c
- Zhdankin/matrix4.c
еще такой вопрос: в файле с выполненными домашними работами у меня в полях Циклы 1,2 и угадай число стоят поля белого цвета, хотя я все это показывал еще очень давно. это так и должно быть?
> двум. массивы Жданкин

- Belyaev N/Teylor.c
Всё вычисляется хорошо(при адекватных значениях x и N), но при больших значениях current уходит в -inf и ломает всё. Не знаю как это исправить.
> Ряд Тейлора cos(x) и ch(x). Беляев Н.

- RyadTeilora.c
Создал одну функцию для расчета формула Тейлора(taylor_series), переменные в начале блока обЪявлены.
> Teilor_3_Vlasov

- Zhdankin/Bulls_Cows update.c
- Zhdankin/str8.c
Примеры входных данных(m - место, r - ряд)
//25.10.2023 Cinderella m1 r2
//Lion_Heart 05.07.2023 r35 m25
//11.11.2023 r5 m90 Ice_Queen
//25.10.2023 r7 My_little_pony m11
//11.11.2023 m9 Thunder_Strike r7
//11.11.2023 r7 Space_Odyssey m4
> Жданкин строки и структуры вар 8

- kovalev/teylor.c
передача функции по указателю действительно классная штука
> formula teylora

- Struct_Strok.c
Изменил функцию "parseLine", добавив в нее проверки (рассмотрел  длину строки токена - если она равна 4, предполагаем, что это год , иначе - это количество страниц.)
> Vlasov_struct_strok

- barkalova/ряд Тейлора.cpp
Я написала программу, которая считает экспоненту и синус через ряд Тейлора.
> Create ряд Тейлора.cpp

- Kolobyanin/25 2d massiv.c
- Kolobyanin/8 -  2d massiv.c
- Kolobyanin/Teylor.c
- Kolobyanin/Ugadayka var2.c
- Kolobyanin/array 32.c
- Kolobyanin/massiv 18.c
Добавил ряд Тейлора
В 25 двумерные массивы, добавил динамическое выделение памяти и освобождение  памяти
В 8 двумерные, добавил освобождение памяти
В 32 одномерные, исправил ввод массива
В 18 одномерные, исправил условие цикла
В угадайке убрал while(1)
> Ряд Тейлора Колобянин

- gorkov/Teylor.c
в 16ой if только для визуального равенства строк
> Gorkov, Teylor_C

- kovalev/string_struct_file.c
Только запросы не седлал и работу с файлами
> string_struct_file.c

- Babkin/2 - ar2d.c
- Babkin/26 - ar2d.c
- Babkin/Row of Taylor.c
- Babkin/Rows of TAYLOR.c
- Babkin/Sorts.c
Всё таки не нашлось тогда свободного времени. Скинул ряд тейлора(файл Rows of TAYLOR) ,потом скину больше. Не знаю, успею ли переписать все сортировки и структуры с файлами до 11 часов. Если потребуется буду работать над этим всю ночь.ТО, что до рядов тейлора не смотреть.
> Бабкин Ряд Тейлора. 

- Zhdankin/Taylor6.c
> Жданкин Тейлор для логарифма

- Ilyushkin N/LabaSortArrays.c
- Ilyushkin N/LabaSortArraysredacted...c
- Ilyushkin N/LabaSortArraysredacted.c
- Ilyushkin N/array2d-15.c
- Ilyushkin N/array2d23+malloc....c
- Ilyushkin N/array2d23+malloc.c
- Ilyushkin N/array2d23.c
- Ilyushkin N/bulls and cows attempt 3.c
- Ilyushkin N/kasa.c
- Ilyushkin N/kontrolnaia rabota.c
- Ilyushkin N/massiv 24.c
- Ilyushkin N/massiv18.c
- Ilyushkin N/massiv18withmalloc...c
- Ilyushkin N/massiv18withmalloc.c
- Ilyushkin N/teilor 9 + exp.c
- Ilyushkin N/teilor+....c
- Ilyushkin N/teilor+.c
- Ilyushkin N/zad 19 ilyushkin.c
еще раз извините что все скидываю в последний момент. В большой программе с сортировками подписал что за что отвечает. До сих пор не понял как включить поддержку русского языка(
> программы с массивов 2d до ряда тейлора

- Vector.cpp
программа работает, но почему-то при отладке, после вывода консоли получаю: Инструкция точки останова (оператор __debugbreak()
> Klass-vector_Vlasov

- Kirillov/Gauss/gauss.cpp
- Kirillov/Gauss/gauss.h
- Kirillov/Gauss/main.cpp
- Kirillov/Kassa/Check.cpp
- Kirillov/Kassa/Check.h
- Kirillov/Kassa/Magazin.cpp
- Kirillov/Kassa/Magazin.h
- Kirillov/Kassa/Tovar.cpp
- Kirillov/Kassa/Tovar.h
- Kirillov/Kassa/check.txt
- Kirillov/Kassa/kasss2.cpp
- Kirillov/Kassa/requests.txt
- Kirillov/Kassa/sklad.txt
- Kirillov/SimpleClass/Fraction.h
- Kirillov/SimpleClass/SImpleCL.cpp
- Kirillov/SimpleClass/main.cpp
> SimpleClassDrobi
